import pool from "./db.js";

/**
 * =====================================================
 * Auto Database Schema Initialization & Migration
 * Ensures all required PostgreSQL tables & seed data exist
 * =====================================================
 */
export async function initDatabaseSchema() {
  try {
    // 1. Check if "users" table exists
    const checkUsers = await pool.query(`
      SELECT EXISTS (
        SELECT FROM information_schema.tables 
        WHERE table_schema = 'public' AND table_name = 'users'
      );
    `);

    const usersExist = checkUsers.rows[0]?.exists;

    if (!usersExist) {
      console.log("? Initializing database schema (users table not found)...");

      await pool.query(`
        CREATE SEQUENCE IF NOT EXISTS employee_code_seq START WITH 1001;
        CREATE SEQUENCE IF NOT EXISTS campaign_code_seq START WITH 1001;
        CREATE SEQUENCE IF NOT EXISTS lead_code_seq START WITH 1001;

        CREATE TABLE IF NOT EXISTS users (
          id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          full_name       VARCHAR(150) NOT NULL,
          email           VARCHAR(255) NOT NULL UNIQUE,
          password        VARCHAR(255) NOT NULL,
          role            VARCHAR(30) NOT NULL DEFAULT 'COUNSELLOR',
          is_active       BOOLEAN NOT NULL DEFAULT TRUE,
          is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
          email_verified  BOOLEAN NOT NULL DEFAULT FALSE,
          last_login      TIMESTAMPTZ,
          created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS departments (
          id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          department_name VARCHAR(150) NOT NULL UNIQUE,
          description     TEXT,
          status          BOOLEAN NOT NULL DEFAULT TRUE,
          created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS employees (
          id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id                 BIGINT UNIQUE REFERENCES users(id) ON DELETE SET NULL,
          employee_code           VARCHAR(30) NOT NULL UNIQUE,
          full_name               VARCHAR(150) NOT NULL,
          email                   VARCHAR(255) NOT NULL UNIQUE,
          mobile                  VARCHAR(20) NOT NULL UNIQUE,
          department_id           BIGINT REFERENCES departments(id) ON DELETE SET NULL,
          designation             VARCHAR(100),
          role                    VARCHAR(30) NOT NULL DEFAULT 'COUNSELLOR',
          employment_type         VARCHAR(30) NOT NULL DEFAULT 'FULL_TIME',
          status                  VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
          joining_date            DATE,
          date_of_birth           DATE,
          gender                  VARCHAR(30),
          profile_image           TEXT,
          address                 TEXT,
          emergency_contact_name  VARCHAR(150),
          emergency_contact       VARCHAR(20),
          created_by              BIGINT,
          updated_by              BIGINT,
          deleted_by              BIGINT,
          created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          deleted_at              TIMESTAMPTZ,
          is_deleted              BOOLEAN NOT NULL DEFAULT FALSE
        );

        CREATE TABLE IF NOT EXISTS campaigns (
          id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          campaign_code     VARCHAR(40) NOT NULL UNIQUE,
          campaign_name     VARCHAR(200) NOT NULL,
          platform          VARCHAR(100),
          source            VARCHAR(100),
          budget            NUMERIC(14, 2) NOT NULL DEFAULT 0,
          landing_page_url  TEXT,
          description       TEXT,
          start_date        DATE,
          end_date          DATE,
          status            VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
          created_by        BIGINT,
          updated_by        BIGINT,
          created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          is_deleted        BOOLEAN NOT NULL DEFAULT FALSE
        );

        CREATE TABLE IF NOT EXISTS leads (
          id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          lead_code           VARCHAR(40) NOT NULL UNIQUE,
          campaign_id         BIGINT REFERENCES campaigns(id) ON DELETE SET NULL,
          full_name           VARCHAR(150) NOT NULL,
          mobile              VARCHAR(20) NOT NULL,
          alternate_mobile    VARCHAR(20),
          phone               VARCHAR(20),
          email               VARCHAR(255),
          city                VARCHAR(100),
          state               VARCHAR(100),
          country             VARCHAR(100) NOT NULL DEFAULT 'India',
          interested_course   VARCHAR(200),
          preferred_centre    VARCHAR(200),
          source              VARCHAR(100) NOT NULL,
          platform            VARCHAR(100),
          landing_page_url    TEXT,
          utm_source          VARCHAR(255),
          utm_medium          VARCHAR(255),
          utm_campaign        VARCHAR(255),
          utm_content         VARCHAR(255),
          utm_term            VARCHAR(255),
          external_lead_id    VARCHAR(255),
          status              VARCHAR(30) NOT NULL DEFAULT 'NEW',
          priority            VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
          assigned_to         BIGINT REFERENCES employees(id) ON DELETE SET NULL,
          remarks             TEXT,
          feedback            TEXT,
          next_followup       TIMESTAMPTZ,
          is_duplicate        BOOLEAN NOT NULL DEFAULT FALSE,
          duplicate_of        BIGINT,
          received_count      INTEGER NOT NULL DEFAULT 1,
          last_received_at    TIMESTAMPTZ,
          captured_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          created_by          BIGINT,
          updated_by          BIGINT,
          created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          is_deleted          BOOLEAN NOT NULL DEFAULT FALSE
        );

        CREATE TABLE IF NOT EXISTS lead_assignments (
          id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          lead_id               BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
          assigned_by           BIGINT,
          assigned_to           BIGINT NOT NULL,
          previous_assigned_to  BIGINT,
          remarks               TEXT,
          assigned_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS lead_followups (
          id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          lead_id             BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
          employee_id         BIGINT NOT NULL,
          followup_type       VARCHAR(30) NOT NULL DEFAULT 'CALL',
          status              VARCHAR(30) NOT NULL DEFAULT 'PENDING',
          outcome             VARCHAR(100),
          priority            VARCHAR(20) DEFAULT 'MEDIUM',
          next_followup_at    TIMESTAMPTZ,
          remarks             TEXT,
          created_by          BIGINT,
          updated_by          BIGINT,
          created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
          is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
          deleted_at          TIMESTAMPTZ,
          deleted_by          BIGINT
        );

        CREATE TABLE IF NOT EXISTS lead_notes (
          id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          lead_id         BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
          note            TEXT NOT NULL,
          created_by      BIGINT,
          created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS lead_timeline (
          id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          lead_id         BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
          employee_id     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
          activity_type   VARCHAR(100),
          title           VARCHAR(255),
          description     TEXT,
          old_value       TEXT,
          new_value       TEXT,
          action          VARCHAR(100),
          remarks         TEXT,
          created_by      BIGINT,
          created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS lead_activity_logs (
          id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          lead_id         BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
          activity        VARCHAR(100) NOT NULL,
          description     TEXT,
          performed_by    BIGINT,
          created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS refresh_tokens (
          id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          token           TEXT NOT NULL UNIQUE,
          expires_at      TIMESTAMPTZ NOT NULL,
          created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS password_resets (
          id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          reset_token     TEXT NOT NULL UNIQUE,
          expires_at      TIMESTAMPTZ NOT NULL,
          used            BOOLEAN NOT NULL DEFAULT FALSE,
          created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS lead_sources (
          id SERIAL PRIMARY KEY,
          name TEXT NOT NULL UNIQUE,
          description TEXT,
          is_active BOOLEAN DEFAULT TRUE,
          is_deleted BOOLEAN DEFAULT FALSE,
          created_by INTEGER,
          updated_by INTEGER,
          created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
          updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
        );
      `);

      // Seed initial Admin & Counsellor accounts
      await pool.query(`
        INSERT INTO users (id, full_name, email, password, role, is_active, is_deleted, email_verified) VALUES
          (1, 'Divyanshu Mishra', 'divyanshu@gmail.com', '$2b$10$FdjvHaE0Zin7vtvsbFuLWuRVF7TZJjnKmwuDl/XTc16F6gC9aphoe', 'ADMIN', TRUE, FALSE, TRUE),
          (12, 'Divyanshu Mishra', 'divyanshu001@gmail.com', '$2b$10$Lrqdo1an.uDa35M6l3Fj8.xKRME4WMcrR.4bsSyVlulM5Az/02A9i', 'ADMIN', TRUE, FALSE, TRUE),
          (14, 'Rohit Kumar', 'rohit.kumars@iemlms.com', '$2b$10$0CkPoAU.v8LSO3eRVpvtaO8L6WVMGe9oY/q2z9KVUQ5zU62ahZaxK', 'COUNSELLOR', TRUE, FALSE, TRUE)
        ON CONFLICT DO NOTHING;

        INSERT INTO departments (id, department_name, description, status)
        VALUES (1, 'Admissions & Sales', 'Admissions & Student Counselling', TRUE)
        ON CONFLICT DO NOTHING;

        INSERT INTO employees (id, user_id, employee_code, full_name, email, mobile, department_id, designation, role, status)
        VALUES 
          (1, 14, 'EMP000005', 'Rohit Kumar', 'rohit.kumars@iemlms.com', '9876543201', 1, 'Senior Counsellor', 'COUNSELLOR', 'ACTIVE'),
          (2, 12, 'EMP000001', 'Divyanshu Mishra', 'divyanshu001@gmail.com', '9876543200', 1, 'Director', 'ADMIN', 'ACTIVE')
        ON CONFLICT DO NOTHING;

        INSERT INTO lead_sources (name, description, is_active) VALUES
          ('Website', 'Captured via website form', TRUE),
          ('Google Ads', 'Paid search campaigns', TRUE),
          ('Meta', 'Meta / Facebook campaigns', TRUE),
          ('Referral', 'Referred by partner or student', TRUE),
          ('Walk In', 'Direct walk in enquiry', TRUE)
        ON CONFLICT DO NOTHING;
      `);

      console.log("? Core database tables and seed users initialized successfully.");
    }

    // 2. Ensure "admissions" & "admission_payments" tables exist
    await pool.query(`
      CREATE TABLE IF NOT EXISTS admissions (
        id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        lead_id                 BIGINT REFERENCES leads(id) ON DELETE SET NULL,
        admission_number        VARCHAR(40) UNIQUE,
        student_name            VARCHAR(150) NOT NULL,
        mobile                  VARCHAR(20) NOT NULL,
        email                   VARCHAR(255),
        course_name             VARCHAR(200) NOT NULL,
        centre                  VARCHAR(100),
        total_fee               NUMERIC(14, 2) NOT NULL DEFAULT 0,
        paid_fee                NUMERIC(14, 2) NOT NULL DEFAULT 0,
        pending_fee             NUMERIC(14, 2) NOT NULL DEFAULT 0,
        fee_status              VARCHAR(30) NOT NULL DEFAULT 'PARTIAL',
        next_due_date           DATE,
        assigned_counsellor_id  BIGINT REFERENCES employees(id) ON DELETE SET NULL,
        created_by              BIGINT REFERENCES users(id) ON DELETE SET NULL,
        remarks                 TEXT,
        created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );

      CREATE TABLE IF NOT EXISTS admission_payments (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        admission_id    BIGINT NOT NULL REFERENCES admissions(id) ON DELETE CASCADE,
        amount          NUMERIC(14, 2) NOT NULL CHECK (amount > 0),
        payment_mode    VARCHAR(50) NOT NULL DEFAULT 'UPI',
        receipt_number  VARCHAR(100),
        payment_date    DATE NOT NULL DEFAULT CURRENT_DATE,
        remarks         TEXT,
        recorded_by     BIGINT REFERENCES users(id) ON DELETE SET NULL,
        created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    `);

    // Ensure sequences align
    try {
      await pool.query(`
        SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1), true);
        SELECT setval(pg_get_serial_sequence('employees', 'id'), COALESCE((SELECT MAX(id) FROM employees), 1), true);
      `);
    } catch {}

    console.log("? Database schema check passed.");
  } catch (error) {
    console.error("? Database initialization error:", error.message);
  }
}
