-- IEM Admissions CRM / LMS database schema
-- PostgreSQL 16+
-- Run with: psql -U postgres -d iem_lms -f server/iem_lms.sql

BEGIN;

CREATE SEQUENCE IF NOT EXISTS employee_code_seq START WITH 1001;
CREATE SEQUENCE IF NOT EXISTS campaign_code_seq START WITH 1001;
CREATE SEQUENCE IF NOT EXISTS lead_code_seq START WITH 1001;

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(150) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    role            VARCHAR(30) NOT NULL DEFAULT 'COUNSELLOR',
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
    email_verified  BOOLEAN NOT NULL DEFAULT FALSE,
    last_login      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'MANAGER', 'COUNSELLOR', 'EMPLOYEE', 'admin', 'manager', 'counsellor', 'employee'))
);

CREATE TABLE IF NOT EXISTS departments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(150) NOT NULL UNIQUE,
    description     TEXT,
    status          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employees (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT UNIQUE REFERENCES users(id) ON DELETE SET NULL,
    employee_code           VARCHAR(30) NOT NULL UNIQUE,
    full_name               VARCHAR(150) NOT NULL,
    email                   VARCHAR(255) NOT NULL UNIQUE,
    mobile                  VARCHAR(20) NOT NULL UNIQUE,
    department_id           BIGINT REFERENCES departments(id) ON DELETE SET NULL,
    designation             VARCHAR(100),
    role                    VARCHAR(30) NOT NULL DEFAULT 'COUNSELLOR',
    employment_type         VARCHAR(30) NOT NULL DEFAULT 'FULL_TIME',
    status                  VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    joining_date            DATE,
    date_of_birth           DATE,
    gender                  VARCHAR(30),
    profile_image           TEXT,
    address                 TEXT,
    emergency_contact_name  VARCHAR(150),
    emergency_contact       VARCHAR(20),
    created_by              BIGINT,
    updated_by              BIGINT,
    deleted_by              BIGINT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at              TIMESTAMPTZ,
    is_deleted              BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT employees_role_check CHECK (role IN ('ADMIN', 'MANAGER', 'COUNSELLOR', 'EMPLOYEE')),
    CONSTRAINT employees_status_check CHECK (status IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'SUSPENDED')),
    CONSTRAINT employees_employment_type_check CHECK (employment_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN'))
);

CREATE TABLE IF NOT EXISTS campaigns (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_code     VARCHAR(40) NOT NULL UNIQUE,
    campaign_name     VARCHAR(200) NOT NULL,
    platform          VARCHAR(100),
    source            VARCHAR(100),
    budget            NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (budget >= 0),
    landing_page_url  TEXT,
    description       TEXT,
    start_date        DATE,
    end_date          DATE,
    status            VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_by        BIGINT,
    updated_by        BIGINT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted        BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT campaigns_dates_check CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT campaigns_status_check CHECK (status IN ('ACTIVE', 'INACTIVE', 'COMPLETED', 'DRAFT'))
);

CREATE TABLE IF NOT EXISTS leads (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_code           VARCHAR(40) NOT NULL UNIQUE,
    campaign_id         BIGINT REFERENCES campaigns(id) ON DELETE SET NULL,
    full_name           VARCHAR(150) NOT NULL,
    mobile              VARCHAR(20) NOT NULL,
    alternate_mobile    VARCHAR(20),
    phone               VARCHAR(20), -- retained for legacy assignment queries
    email               VARCHAR(255),
    city                VARCHAR(100),
    state               VARCHAR(100),
    country             VARCHAR(100) NOT NULL DEFAULT 'India',
    interested_course   VARCHAR(200),
    preferred_centre    VARCHAR(200),
    source              VARCHAR(100) NOT NULL,
    platform            VARCHAR(100),
    landing_page_url    TEXT,
    utm_source          VARCHAR(255),
    utm_medium          VARCHAR(255),
    utm_campaign        VARCHAR(255),
    utm_content         VARCHAR(255),
    utm_term            VARCHAR(255),
    external_lead_id    VARCHAR(255),
    status              VARCHAR(30) NOT NULL DEFAULT 'NEW',
    priority            VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    assigned_to         BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    remarks             TEXT,
    feedback            TEXT,
    next_followup       TIMESTAMPTZ,
    is_duplicate        BOOLEAN NOT NULL DEFAULT FALSE,
    duplicate_of        BIGINT,
    received_count      INTEGER NOT NULL DEFAULT 1,
    last_received_at    TIMESTAMPTZ,
    captured_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          BIGINT,
    updated_by          BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT leads_status_check CHECK (status IN ('NEW', 'CONTACTED', 'FOLLOW_UP', 'FOLLOW_UP_REQUIRED', 'QUALIFIED', 'INTERESTED', 'ENROLLED', 'ADMISSION_DONE', 'ADMITTED', 'LOST', 'REJECTED', 'HOT', 'WARM', 'COLD', 'VISITED', 'WALK_IN', 'NOT_INTERESTED', 'PENDING', 'COMPLETED', 'new', 'contacted', 'follow_up', 'interested', 'admission_done', 'not_interested', 'lost', 'enrolled')),
    CONSTRAINT leads_priority_check CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT', 'low', 'medium', 'high', 'urgent'))
);

CREATE TABLE IF NOT EXISTS lead_assignments (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id               BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    -- Legacy records may contain a user ID rather than an employee ID here.
    assigned_by           BIGINT,
    assigned_to           BIGINT NOT NULL,
    previous_assigned_to  BIGINT,
    remarks               TEXT,
    assigned_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lead_followups (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id             BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    -- Legacy follow-ups may refer to an employee record that was later removed.
    employee_id         BIGINT NOT NULL,
    followup_type       VARCHAR(30) NOT NULL DEFAULT 'CALL',
    status              VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    outcome             VARCHAR(100),
    priority            VARCHAR(20) DEFAULT 'MEDIUM',
    next_followup_at    TIMESTAMPTZ,
    remarks             TEXT,
    created_by          BIGINT,
    updated_by          BIGINT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ,
    deleted_by          BIGINT,
    CONSTRAINT lead_followups_type_check CHECK (followup_type IN ('CALL', 'WHATSAPP', 'EMAIL', 'SMS', 'MEETING', 'OTHER')),
    CONSTRAINT lead_followups_status_check CHECK (status IN ('PENDING', 'COMPLETED', 'CANCELLED', 'MISSED', 'RESCHEDULED')),
    CONSTRAINT lead_followups_priority_check CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE TABLE IF NOT EXISTS lead_notes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id         BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    note            TEXT NOT NULL,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lead_timeline (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id         BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    employee_id     BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    activity_type   VARCHAR(100),
    title           VARCHAR(255),
    description     TEXT,
    old_value       TEXT,
    new_value       TEXT,
    action          VARCHAR(100), -- compatibility with the older timeline repository
    remarks         TEXT,
    created_by      BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lead_activity_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id         BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
    activity        VARCHAR(100) NOT NULL,
    description     TEXT,
    performed_by    BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token           TEXT NOT NULL UNIQUE,
    expires_at      TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS password_resets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reset_token     TEXT NOT NULL UNIQUE,
    expires_at      TIMESTAMPTZ NOT NULL,
    used            BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_employees_active_department ON employees (department_id) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_campaigns_active_status ON campaigns (status) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_leads_active_assigned_to ON leads (assigned_to) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_leads_active_status ON leads (status) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_leads_campaign_id ON leads (campaign_id);
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads (created_at DESC) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_lead_assignments_lead_id ON lead_assignments (lead_id, assigned_at DESC);
CREATE INDEX IF NOT EXISTS idx_followups_due ON lead_followups (employee_id, next_followup_at) WHERE is_deleted = FALSE AND status = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_followups_lead_id ON lead_followups (lead_id);
CREATE INDEX IF NOT EXISTS idx_timeline_lead_id ON lead_timeline (lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lead_notes_lead_id ON lead_notes (lead_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX IF NOT EXISTS idx_password_resets_token ON password_resets (reset_token) WHERE used = FALSE;

-- Seed data exported from the configured development database on 2026-07-25.
-- Refresh tokens and password-reset tokens are intentionally not exported.
-- Inserts are idempotent, so this file can be run more than once.

INSERT INTO users (id, full_name, email, password, role, created_at, is_active, is_deleted, last_login, updated_at, email_verified) VALUES
  (1, 'System Administrator', 'admin@iemlms.com', '$2b$10$FdjvHaE0Zin7vtvsbFuLWuRVF7TZJjnKmwuDl/XTc16F6gC9aphoe', 'ADMIN', '2026-06-27T11:15:30.995Z', TRUE, FALSE, NULL, '2026-07-01T03:17:05.579Z', TRUE),
  (2, 'Admissions Counsellor', 'counsellor@iemlms.com', '$2b$10$0CkPoAU.v8LSO3eRVpvtaO8L6WVMGe9oY/q2z9KVUQ5zU62ahZaxK', 'COUNSELLOR', '2026-07-23T07:22:15.562Z', TRUE, FALSE, NULL, '2026-07-24T09:01:27.773Z', TRUE)
ON CONFLICT (id) DO NOTHING;

-- Lead Sources table
CREATE TABLE IF NOT EXISTS lead_sources (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  is_deleted BOOLEAN DEFAULT FALSE,
  created_by INTEGER,
  updated_by INTEGER,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO lead_sources (name, description, is_active, created_at) VALUES
  ('Website', 'Captured via website form', TRUE, '2026-06-27T11:00:00.000Z'),
  ('Google Ads', 'Paid search campaigns', TRUE, '2026-06-27T11:00:00.000Z'),
  ('Meta', 'Meta / Facebook campaigns', TRUE, '2026-06-27T11:00:00.000Z'),
  ('Referral', 'Referred by partner or student', TRUE, '2026-06-27T11:00:00.000Z')
ON CONFLICT (name) DO NOTHING;

INSERT INTO departments (id, department_name, description, status, created_at, updated_at)
VALUES (1, 'Admissions & Sales', 'Admissions & Student Counselling', TRUE, '2026-06-28T06:33:25.689Z', '2026-06-28T06:33:25.689Z') ON CONFLICT (id) DO NOTHING;

INSERT INTO employees (id, user_id, employee_code, full_name, email, mobile, department_id, designation, role, employment_type, status, joining_date, date_of_birth, gender, profile_image, address, emergency_contact_name, emergency_contact, created_by, updated_by, deleted_by, created_at, updated_at, deleted_at, is_deleted)
VALUES 
  (1, 1, 'EMP000001', 'System Administrator', 'admin@iemlms.com', '9876543200', 1, 'Director', 'ADMIN', 'FULL_TIME', 'ACTIVE', '2026-07-01', '1990-01-01', 'MALE', NULL, 'New Delhi', 'Admin Office', '9876500000', 1, 1, NULL, '2026-07-01T05:09:10.141Z', '2026-07-24T08:22:22.986Z', NULL, FALSE),
  (2, 2, 'EMP000002', 'Admissions Counsellor', 'counsellor@iemlms.com', '9876543201', 1, 'Senior Counsellor', 'COUNSELLOR', 'FULL_TIME', 'ACTIVE', '2026-07-21', '1995-05-15', 'MALE', NULL, 'New Delhi', 'Counselling Desk', '9876500001', 1, 1, NULL, '2026-07-23T07:22:15.562Z', '2026-07-23T08:06:34.602Z', NULL, FALSE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO campaigns (id, campaign_code, campaign_name, platform, source, budget, landing_page_url, description, start_date, end_date, status, created_by, updated_by, created_at, updated_at, is_deleted) VALUES
  (1, 'CAM000001', 'BCA Admission 2027 Updated', 'GOOGLE', 'Google Search Ads', 75000.00, 'https://iem.edu.in/admission', 'Updated Campaign', '2026-07-02', '2026-09-15', 'ACTIVE', 12, 12, '2026-07-02T09:10:42.724Z', '2026-07-14T16:07:56.423Z', TRUE),
  (2, 'CAM000002', 'Diploma  in Event Management', 'META', 'Meta ads vidoes', 10000.00, 'https://iemworld.in', 'best diploma for event manage', '2026-07-10', '2026-08-25', 'ACTIVE', 12, NULL, '2026-07-14T17:38:26.121Z', '2026-07-14T17:38:26.121Z', FALSE)
ON CONFLICT DO NOTHING;

INSERT INTO leads (id, lead_code, campaign_id, full_name, mobile, alternate_mobile, email, city, state, country, interested_course, source, platform, landing_page_url, utm_source, utm_medium, utm_campaign, utm_content, utm_term, external_lead_id, status, priority, assigned_to, remarks, next_followup, is_duplicate, duplicate_of, received_count, last_received_at, captured_at, created_by, updated_by, created_at, updated_at, is_deleted, preferred_centre, feedback) VALUES
  (1, 'LEAD000003', 1, 'Rahul Sharma', '9876543210', NULL, 'rahul@gmail.com', 'Delhi', NULL, 'India', NULL, 'META', NULL, NULL, 'facebook', 'paid_social', 'bca_admission_2027', 'video_1', 'bca', NULL, 'QUALIFIED', 'MEDIUM', 1, NULL, NULL, FALSE, NULL, 1, '2026-07-02T10:08:47.726Z', '2026-07-02T10:13:17.202Z', NULL, 12, '2026-07-02T10:08:47.726Z', '2026-07-23T08:17:40.290Z', FALSE, NULL, NULL),
  (3, 'LEAD000005', 1, 'Aman Verma', '9876543218', NULL, 'aman.verma@gmail.com', 'Noida', NULL, 'India', NULL, 'META', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NEW', 'MEDIUM', 1, 'Interested in Data Science course.', NULL, FALSE, NULL, 1, '2026-07-12T02:54:38.771Z', '2026-07-12T02:54:38.771Z', 12, 12, '2026-07-12T02:54:38.771Z', '2026-07-23T08:17:40.290Z', FALSE, NULL, NULL),
  (4, 'LEAD000006', 1, 'Priya Sharma', '9876543211', NULL, 'priya.sharma@gmail.com', 'Faridabad', NULL, 'India', NULL, 'GOOGLE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NEW', 'HIGH', 1, 'Asked for scholarship details.', NULL, FALSE, NULL, 1, '2026-07-12T03:01:32.971Z', '2026-07-12T03:01:32.971Z', 12, 12, '2026-07-12T03:01:32.971Z', '2026-07-23T08:17:40.290Z', FALSE, NULL, NULL),
  (6, 'LEAD000008', 1, 'Rohit Singh', '9876543212', NULL, 'rohit.singh@gmail.com', 'Delhi', NULL, 'India', NULL, 'WEBSITE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NEW', 'LOW', 1, 'Requested callback tomorrow.', NULL, FALSE, NULL, 1, '2026-07-12T03:02:40.323Z', '2026-07-12T03:02:40.323Z', 12, 12, '2026-07-12T03:02:40.323Z', '2026-07-23T08:17:40.290Z', FALSE, NULL, NULL),
  (7, 'LEAD000009', 1, 'Rohit Singh', '9876543219', NULL, 'rohit@gmail.com', 'Lucknow', 'UP', 'India', 'BCA', 'WEBSITE', 'GOOGLE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'REJECTED', 'HIGH', 1, NULL, NULL, FALSE, NULL, 1, '2026-07-14T10:41:30.127Z', '2026-07-14T10:41:30.142Z', 12, 14, '2026-07-14T10:41:30.127Z', '2026-07-24T08:11:46.813Z', FALSE, 'Lucknow', 'student joins another institution'),
  (8, 'LEAD000010', 1, 'Rahul Sharma', '9876543215', '9876543211', 'rahul.sharma@example.com', 'Delhi', 'Delhi', 'India', 'Data Science', 'GOOGLE', 'WEBSITE', 'https://iemworld.in/data-science', 'google', 'cpc', 'july_campaign', 'banner_1', 'data science course', 'FB123456', 'COMPLETED', 'MEDIUM', 1, 'Interested in weekend batch', '2026-07-25T04:30:00.000Z', FALSE, NULL, 1, '2026-07-23T08:14:22.366Z', '2026-07-23T08:14:22.379Z', 12, 14, '2026-07-23T08:14:22.366Z', '2026-07-24T08:10:50.460Z', FALSE, 'Delhi', NULL)
ON CONFLICT DO NOTHING;

INSERT INTO lead_assignments (id, lead_id, assigned_by, assigned_to, previous_assigned_to, remarks, assigned_at) VALUES
  (1, 1, 12, 2, NULL, 'Assigned by Admin', '2026-07-04T03:22:15.573Z'),
  (2, 1, 12, 1, 2, 'Transferred to Rahul', '2026-07-04T06:39:59.144Z')
ON CONFLICT DO NOTHING;

INSERT INTO lead_followups (id, lead_id, employee_id, followup_type, status, outcome, priority, next_followup_at, remarks, created_by, updated_by, is_deleted, created_at, updated_at, deleted_at, deleted_by) VALUES
  (1, 1, 2, 'CALL', 'RESCHEDULED', 'INTERESTED', NULL, '2026-07-15T04:30:00.000Z', 'Student requested callback.', 12, 12, TRUE, '2026-07-04T07:13:31.609Z', '2026-07-04T09:56:13.694Z', NULL, NULL),
  (2, 1, 1, 'MEETING', 'COMPLETED', 'INTERESTED', 'MEDIUM', '2026-08-03T05:30:00.000Z', 'Student is interested in admission.', 12, 12, FALSE, '2026-07-21T09:38:18.868Z', '2026-07-21T11:14:44.049Z', NULL, NULL),
  (3, 1, 1, 'CALL', 'RESCHEDULED', NULL, 'HIGH', '2026-08-15T06:30:00.000Z', 'Student requested another date.', 12, 12, FALSE, '2026-07-21T11:16:56.598Z', '2026-07-21T11:51:25.628Z', NULL, NULL)
ON CONFLICT DO NOTHING;

INSERT INTO lead_timeline (id, lead_id, employee_id, activity_type, title, description, old_value, new_value, created_at) VALUES
  (1, 8, 1, 'STATUS_CHANGED', 'Lead Status Updated', 'Status changed from NEW to COMPLETED.', 'NEW', 'COMPLETED', '2026-07-24T08:10:50.531Z'),
  (2, 7, 1, 'STATUS_CHANGED', 'Lead Status Updated', 'Lead rejected. Reason: student joins another institution', 'NEW', 'REJECTED', '2026-07-24T08:11:46.871Z')
ON CONFLICT DO NOTHING;

INSERT INTO lead_activity_logs (id, lead_id, activity, description, performed_by, created_at) VALUES
  (1, 1, 'LEAD_CREATED', 'Lead captured from public source.', NULL, '2026-07-02T10:08:47.726Z'),
  (2, 1, 'LEAD_UPDATED', 'Existing lead updated from public source.', NULL, '2026-07-02T10:12:38.720Z'),
  (3, 1, 'LEAD_UPDATED', 'Existing lead updated from public source.', NULL, '2026-07-02T10:13:17.202Z'),
  (4, 1, 'FOLLOWUP_CREATED', 'Follow-up created successfully.', 12, '2026-07-21T09:38:18.868Z'),
  (5, 1, 'FOLLOWUP_UPDATED', 'Follow-up updated successfully.', 12, '2026-07-21T10:02:59.455Z'),
  (6, 1, 'FOLLOWUP_COMPLETED', 'Follow-up completed successfully.', 12, '2026-07-21T11:14:44.049Z'),
  (7, 1, 'FOLLOWUP_CREATED', 'Follow-up created successfully.', 12, '2026-07-21T11:16:56.598Z'),
  (8, 1, 'FOLLOWUP_RESCHEDULED', 'Follow-up rescheduled to 2026-08-15T12:00:00.', 12, '2026-07-21T11:17:37.653Z'),
  (9, 1, 'FOLLOWUP_DELETED', 'Follow-up deleted successfully.', 12, '2026-07-21T11:32:56.490Z'),
  (10, 1, 'FOLLOWUP_RESTORED', 'Follow-up restored successfully.', 12, '2026-07-21T11:51:25.628Z')
ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1), true);
SELECT setval(pg_get_serial_sequence('departments', 'id'), COALESCE((SELECT MAX(id) FROM departments), 1), true);
SELECT setval(pg_get_serial_sequence('employees', 'id'), COALESCE((SELECT MAX(id) FROM employees), 1), true);
SELECT setval(pg_get_serial_sequence('campaigns', 'id'), COALESCE((SELECT MAX(id) FROM campaigns), 1), true);
SELECT setval(pg_get_serial_sequence('leads', 'id'), COALESCE((SELECT MAX(id) FROM leads), 1), true);
SELECT setval(pg_get_serial_sequence('lead_assignments', 'id'), COALESCE((SELECT MAX(id) FROM lead_assignments), 1), true);
SELECT setval(pg_get_serial_sequence('lead_followups', 'id'), COALESCE((SELECT MAX(id) FROM lead_followups), 1), true);
SELECT setval(pg_get_serial_sequence('lead_notes', 'id'), COALESCE((SELECT MAX(id) FROM lead_notes), 1), true);
SELECT setval(pg_get_serial_sequence('lead_timeline', 'id'), COALESCE((SELECT MAX(id) FROM lead_timeline), 1), true);
SELECT setval(pg_get_serial_sequence('lead_activity_logs', 'id'), COALESCE((SELECT MAX(id) FROM lead_activity_logs), 1), true);

COMMIT;
